// Code generated by "stringer -type=Status -linecomment"; DO NOT EDIT.

package serv

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Init-1]
	_ = x[Preparing-2]
	_ = x[Working-3]
	_ = x[Paused-4]
	_ = x[Stopping-5]
	_ = x[Stopped-6]
	_ = x[Cleaning-7]
}

const _Status_name = "initpreparingworkingpausedstoppingstoppedCleaning"

var _Status_index = [...]uint8{0, 4, 13, 20, 26, 34, 41, 49}

func (i Status) String() string {
	i -= 1
	if i < 0 || i >= Status(len(_Status_index)-1) {
		return "Status(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Status_name[_Status_index[i]:_Status_index[i+1]]
}
